"""Postgres access for the Database Data Dump pipeline.

Thin, synchronous psycopg2 layer. Two kinds of helper live here:

* **Worker helpers** take an explicit ``conn`` — the data-dump consumer owns one
  connection and drives it serially from a worker thread via
  ``asyncio.to_thread``.
* **One-shot helpers** open (and close) their own connection. They are used by
  request handlers and at startup, where no long-lived connection exists.

A dump job and its per-image progress are stored here too, so a job survives a
reload, a crash, or a power cut and can be resumed exactly where it stopped.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Iterable

import psycopg2
from psycopg2.extras import RealDictCursor, execute_values

from app import config

# One row per detected + classified product. ``id`` is generated by the
# pipeline (the remote's id column is a varchar, so this is a string) and
# ``synced_at`` is left NULL for the sync worker to claim.
_INSERT_SQL = (
    "INSERT INTO product_detections "
    "(id, image_id, class_name, x_center, y_center, bbox_width, bbox_height, model_id) VALUES %s"
)

# (id, image_id, class_name, x_center, y_center, bbox_width, bbox_height, model_id)
DetectionRow = tuple[str, str, str, float, float, float, float, str]

# Job/item bookkeeping. ``product_detections`` is created here too so a fresh
# database works out of the box; on an existing one these are all no-ops.
SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS product_detections (
    id          VARCHAR(64),
    image_id    TEXT,
    class_name  TEXT,
    x_center    DOUBLE PRECISION,
    y_center    DOUBLE PRECISION,
    bbox_width  DOUBLE PRECISION,
    bbox_height DOUBLE PRECISION,
    model_id    VARCHAR(150),
    synced_at   TIMESTAMP
);

-- Existing databases predate these three. Adding a nullable column with no
-- default is a catalogue-only change in Postgres 11+, so this is instant even
-- on the 74M-row table and safe to run at startup.
ALTER TABLE product_detections ADD COLUMN IF NOT EXISTS id VARCHAR(64);
ALTER TABLE product_detections ADD COLUMN IF NOT EXISTS model_id VARCHAR(150);
ALTER TABLE product_detections ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP;

CREATE TABLE IF NOT EXISTS data_dump_jobs (
    job_id          TEXT PRIMARY KEY,
    source_filename TEXT NOT NULL,
    status          TEXT NOT NULL,
    total_images    INTEGER NOT NULL,
    error           TEXT,
    config_key      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at      TIMESTAMPTZ,
    finished_at     TIMESTAMPTZ
);

ALTER TABLE data_dump_jobs ADD COLUMN IF NOT EXISTS config_key TEXT;

-- One row per (image, inference setup): the ledger the skip check reads.
-- Deliberately separate from product_detections, which holds ~228 rows per
-- image -- looking "has this been done?" up there would mean searching a table
-- two orders of magnitude larger than the question needs.
CREATE TABLE IF NOT EXISTS image_inference_runs (
    image_id     TEXT NOT NULL,
    config_key   TEXT NOT NULL,
    detections   INTEGER NOT NULL DEFAULT 0,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (image_id, config_key)
);

CREATE TABLE IF NOT EXISTS data_dump_items (
    job_id       TEXT NOT NULL REFERENCES data_dump_jobs(job_id) ON DELETE CASCADE,
    image_id     TEXT NOT NULL,
    image_url    TEXT NOT NULL,
    status       TEXT NOT NULL DEFAULT 'pending',
    reason       TEXT,
    rows_written INTEGER NOT NULL DEFAULT 0,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (job_id, image_id)
);

CREATE INDEX IF NOT EXISTS data_dump_items_job_status_idx
    ON data_dump_items (job_id, status);

-- Feeds the Runtime page. Partial, so a freshly uploaded CSV's pending rows
-- never sit between the reader and the events it wants.
CREATE INDEX IF NOT EXISTS data_dump_items_activity_idx
    ON data_dump_items (updated_at DESC) WHERE status <> 'pending';

-- One row per distinct inference setup. `config_key` is the derived identity
-- (model file hashes + SAHI mode + thresholds + label selection); `model_id` is
-- the human-readable name that goes onto every detection row and travels to the
-- remote. New setups register themselves the first time they are used.
CREATE TABLE IF NOT EXISTS model_registry (
    model_id             VARCHAR(150) PRIMARY KEY,
    config_key           VARCHAR(64)  NOT NULL UNIQUE,
    detection_model      TEXT,
    classification_model TEXT,
    use_sahi             BOOLEAN,
    detection_conf       DOUBLE PRECISION,
    classifier_threshold DOUBLE PRECISION,
    known_label_count    INTEGER,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    notes                TEXT
);

-- Small key/value store. Holds the sync on/off flag, which the API writes and
-- the standalone sync worker reads -- they are separate processes now, so the
-- database is what they agree through.
CREATE TABLE IF NOT EXISTS app_settings (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
"""

# Built separately: on an existing product_detections table these take minutes,
# so they are never part of startup. See app/maintenance.py.
PRODUCT_DETECTIONS_INDEXES = [
    (
        "product_detections_image_id_idx",
        "CREATE INDEX CONCURRENTLY IF NOT EXISTS product_detections_image_id_idx "
        "ON product_detections (image_id)",
    ),
    (
        "product_detections_id_idx",
        "CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS product_detections_id_idx "
        "ON product_detections (id)",
    ),
    # Partial: it only covers rows still waiting to be sent, so it shrinks as the
    # backlog drains instead of growing with the table.
    (
        "product_detections_unsynced_idx",
        "CREATE INDEX CONCURRENTLY IF NOT EXISTS product_detections_unsynced_idx "
        "ON product_detections (id) WHERE synced_at IS NULL",
    ),
]

# A job in one of these states has work left that a resume can pick up.
RESUMABLE_STATUSES = ("interrupted", "failed", "canceled")


def _now() -> datetime:
    return datetime.now(timezone.utc)


def connect(autocommit: bool = False):
    """Open a new Postgres connection using the configured credentials."""
    conn = psycopg2.connect(
        host=config.DB_HOST,
        port=config.DB_PORT,
        dbname=config.DB_NAME,
        user=config.DB_USER,
        password=config.DB_PASSWORD,
    )
    conn.autocommit = autocommit
    return conn


def ping() -> None:
    """Raise if the database is unreachable (fail fast before a run starts)."""
    conn = connect()
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT 1")
    finally:
        conn.close()


def ensure_schema() -> None:
    """Create the dump tables if they are not there yet."""
    conn = connect(autocommit=True)
    try:
        with conn.cursor() as cur:
            cur.execute(SCHEMA_SQL)
    finally:
        conn.close()


# ---------- Job lifecycle ----------
def create_job(
    job_id: str, source_filename: str, rows: list[tuple[str, str]], config_key: str | None = None
) -> int:
    """Persist a new job and all its CSV rows in one transaction.

    This is what makes a dump survive a restart: the work queue is on disk
    *before* the caller is told the job started. Returns the number of items
    stored (duplicate ``image_id``s in the CSV collapse into one).
    """
    conn = connect()
    try:
        with conn.cursor() as cur:
            cur.execute(
                "INSERT INTO data_dump_jobs (job_id, source_filename, status, total_images, config_key) "
                "VALUES (%s, %s, 'queued', %s, %s)",
                (job_id, source_filename, len(rows), config_key),
            )
            execute_values(
                cur,
                "INSERT INTO data_dump_items (job_id, image_id, image_url) VALUES %s "
                "ON CONFLICT (job_id, image_id) DO NOTHING",
                [(job_id, image_id, url) for image_id, url in rows],
            )
            cur.execute("SELECT count(*) FROM data_dump_items WHERE job_id = %s", (job_id,))
            stored = int(cur.fetchone()[0])
            cur.execute(
                "UPDATE data_dump_jobs SET total_images = %s WHERE job_id = %s",
                (stored, job_id),
            )
        conn.commit()
        return stored
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def set_job_status(
    conn,
    job_id: str,
    status: str,
    *,
    error: str | None = None,
    started: bool = False,
    finished: bool = False,
) -> None:
    """Update a job's status (and optionally stamp start/finish)."""
    sets = ["status = %s", "error = %s"]
    params: list[Any] = [status, error]
    if started:
        sets.append("started_at = coalesce(started_at, %s)")
        params.append(_now())
    if finished:
        sets.append("finished_at = %s")
        params.append(_now())
    params.append(job_id)
    with conn.cursor() as cur:
        cur.execute(f"UPDATE data_dump_jobs SET {', '.join(sets)} WHERE job_id = %s", params)
    if not conn.autocommit:
        conn.commit()


def load_job(job_id: str) -> dict | None:
    """Read one job row plus its aggregated progress."""
    conn = connect(autocommit=True)
    try:
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute("SELECT * FROM data_dump_jobs WHERE job_id = %s", (job_id,))
            job = cur.fetchone()
            if not job:
                return None
            return {**dict(job), **_counts(cur, job_id)}
    finally:
        conn.close()


def list_jobs(limit: int = 25) -> list[dict]:
    """Recent jobs, newest first, each with its aggregated progress."""
    conn = connect(autocommit=True)
    try:
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute(
                "SELECT * FROM data_dump_jobs ORDER BY created_at DESC LIMIT %s", (limit,)
            )
            jobs = [dict(row) for row in cur.fetchall()]
            return [{**job, **_counts(cur, job["job_id"])} for job in jobs]
    finally:
        conn.close()


def _counts(cur, job_id: str) -> dict:
    """Aggregate per-item progress for a job (done / failed / pending / rows)."""
    cur.execute(
        "SELECT status, count(*) AS n, coalesce(sum(rows_written), 0) AS written "
        "FROM data_dump_items WHERE job_id = %s GROUP BY status",
        (job_id,),
    )
    processed = failed = skipped = pending = written = 0
    for row in cur.fetchall():
        status, n, w = row["status"], int(row["n"]), int(row["written"])
        if status == "done":
            processed, written = n, w
        elif status == "failed":
            failed = n
        elif status == "skipped":
            skipped = n
        else:
            pending += n
    return {
        "processed_images": processed,
        "failed_images": failed,
        "skipped_images": skipped,
        "pending_images": pending,
        "rows_written": written,
    }


def reconcile_interrupted_jobs() -> list[str]:
    """Flag jobs left mid-flight by a crash/restart and return their ids.

    Nothing can be running right after the process starts, so any job still
    marked ``queued``/``running`` was cut off and is safe to reopen.
    """
    conn = connect(autocommit=True)
    try:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE data_dump_jobs SET status = 'interrupted' "
                "WHERE status IN ('queued', 'running') RETURNING job_id"
            )
            return [row[0] for row in cur.fetchall()]
    finally:
        conn.close()


# ---------- Item queue ----------
def pending_items(conn, job_id: str) -> list[tuple[str, str]]:
    """Rows of a job that still need processing, as ``(image_id, image_url)``."""
    with conn.cursor() as cur:
        cur.execute(
            "SELECT image_id, image_url FROM data_dump_items "
            "WHERE job_id = %s AND status = 'pending' ORDER BY image_id",
            (job_id,),
        )
        return [(row[0], row[1]) for row in cur.fetchall()]


def mark_item_failed(conn, job_id: str, image_id: str, reason: str) -> None:
    """Record a per-image failure so a resume does not retry it forever."""
    with conn.cursor() as cur:
        cur.execute(
            "UPDATE data_dump_items SET status = 'failed', reason = %s, updated_at = now() "
            "WHERE job_id = %s AND image_id = %s",
            (reason[:500], job_id, image_id),
        )
    if not conn.autocommit:
        conn.commit()


def skip_already_processed(conn, job_id: str, config_key: str) -> int:
    """Mark this job's images that were already inferred under ``config_key``.

    One set-based statement, not one query per image: a 3 lakh-row CSV would
    otherwise mean 3 lakh round-trips. Postgres joins the job's rows against the
    ledger in a single pass, which stays fast as the ledger grows because the
    join probes a primary-key index rather than scanning.
    """
    with conn.cursor() as cur:
        cur.execute(
            "UPDATE data_dump_items i "
            "   SET status = 'skipped', reason = 'already processed', updated_at = now() "
            "  FROM image_inference_runs r "
            " WHERE i.job_id = %s AND i.status = 'pending' "
            "   AND r.image_id = i.image_id AND r.config_key = %s",
            (job_id, config_key),
        )
        skipped = cur.rowcount
    if not conn.autocommit:
        conn.commit()
    return max(0, skipped)


def complete_item(
    conn,
    job_id: str,
    image_id: str,
    rows: Iterable[DetectionRow],
    config_key: str | None = None,
) -> int:
    """Insert an image's detections **and** mark it done, atomically.

    Both writes share one transaction, so a crash can never leave detections in
    the database with the item still pending — which on resume would reprocess
    the image and duplicate every row. Returns the number of detections written.
    """
    rows = list(rows)
    try:
        with conn.cursor() as cur:
            if rows:
                execute_values(cur, _INSERT_SQL, rows)
            if config_key:
                # Same transaction as the detections, so the ledger can never
                # claim an image is done when its rows were rolled back.
                cur.execute(
                    "INSERT INTO image_inference_runs (image_id, config_key, detections) "
                    "VALUES (%s, %s, %s) ON CONFLICT (image_id, config_key) DO UPDATE "
                    "SET detections = EXCLUDED.detections, processed_at = now()",
                    (image_id, config_key, len(rows)),
                )
            cur.execute(
                "UPDATE data_dump_items SET status = 'done', rows_written = %s, "
                "updated_at = now() WHERE job_id = %s AND image_id = %s",
                (len(rows), job_id, image_id),
            )
        conn.commit()
        return len(rows)
    except Exception:
        conn.rollback()
        raise


# ---------- Settings shared between the API and the sync worker ----------
def get_setting(key: str, default: str | None = None) -> str | None:
    conn = connect(autocommit=True)
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT value FROM app_settings WHERE key = %s", (key,))
            row = cur.fetchone()
            return row[0] if row else default
    finally:
        conn.close()


def set_setting(key: str, value: str) -> None:
    conn = connect(autocommit=True)
    try:
        with conn.cursor() as cur:
            cur.execute(
                "INSERT INTO app_settings (key, value) VALUES (%s, %s) "
                "ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()",
                (key, value),
            )
    finally:
        conn.close()


# ---------- Model registry ----------
def get_model_id(config_key: str) -> str | None:
    """The model_id registered for an inference setup, if it has one."""
    conn = connect(autocommit=True)
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT model_id FROM model_registry WHERE config_key = %s", (config_key,))
            row = cur.fetchone()
            return row[0] if row else None
    finally:
        conn.close()


def register_model(config_key: str, details: dict, fallback_model_id: str) -> str:
    """Return this setup's model_id, registering it the first time it is seen.

    The very first setup registered inherits ``fallback_model_id`` (the existing
    ``model-001-...`` name) so history stays continuous; later ones are numbered
    from it.
    """
    conn = connect(autocommit=True)
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT model_id FROM model_registry WHERE config_key = %s", (config_key,))
            row = cur.fetchone()
            if row:
                return row[0]

            cur.execute("SELECT count(*) FROM model_registry")
            existing = int(cur.fetchone()[0])
            model_id = fallback_model_id if existing == 0 else _next_model_id(cur, details)

            cur.execute(
                "INSERT INTO model_registry (model_id, config_key, detection_model, "
                "  classification_model, use_sahi, detection_conf, classifier_threshold, "
                "  known_label_count) VALUES (%s, %s, %s, %s, %s, %s, %s, %s) "
                "ON CONFLICT (config_key) DO NOTHING",
                (
                    model_id, config_key,
                    details.get("detection_model"), details.get("classification_model"),
                    details.get("use_sahi"), details.get("detection_conf"),
                    details.get("classifier_threshold"), details.get("known_label_count"),
                ),
            )
            cur.execute("SELECT model_id FROM model_registry WHERE config_key = %s", (config_key,))
            return cur.fetchone()[0]
    finally:
        conn.close()


def _next_model_id(cur, details: dict) -> str:
    """Generate the next `model-NNN-<detection>-<classifier>` name."""
    cur.execute("SELECT coalesce(max(substring(model_id from 'model-([0-9]+)')::int), 0) "
                "FROM model_registry WHERE model_id ~ '^model-[0-9]+'")
    seq = int(cur.fetchone()[0]) + 1

    def slug(value: str | None) -> str:
        text = str(value or "unknown").rsplit(".", 1)[0]
        return "".join(ch if ch.isalnum() else "-" for ch in text).strip("-").lower() or "unknown"

    name = f"model-{seq:03d}-{slug(details.get('detection_model'))}-{slug(details.get('classification_model'))}"
    return name[:150]


def list_models() -> list[dict]:
    conn = connect(autocommit=True)
    try:
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute("SELECT * FROM model_registry ORDER BY created_at")
            return [dict(r) for r in cur.fetchall()]
    finally:
        conn.close()


def rename_model(config_key: str, model_id: str) -> None:
    """Give a registered setup a different model_id (e.g. their own naming)."""
    conn = connect(autocommit=True)
    try:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE model_registry SET model_id = %s WHERE config_key = %s",
                (model_id, config_key),
            )
    finally:
        conn.close()


# ---------- Cross-process sync lock ----------
# The API (Instant Sync button) and the standalone worker can both decide to
# sync. Without a lock they would each claim the same unsynced rows and push
# them twice, since a row is only marked sent after the remote commits. A
# session-level advisory lock is held for the duration of a cycle and released
# automatically when the connection closes -- including if the process is killed.
SYNC_LOCK_KEY = 918273645


def try_sync_lock(conn) -> bool:
    """Take the sync lock, or return False if another process holds it."""
    with conn.cursor() as cur:
        cur.execute("SELECT pg_try_advisory_lock(%s)", (SYNC_LOCK_KEY,))
        return bool(cur.fetchone()[0])


def release_sync_lock(conn) -> None:
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT pg_advisory_unlock(%s)", (SYNC_LOCK_KEY,))
    except Exception:  # noqa: BLE001 - closing the connection releases it anyway
        pass


def sync_in_progress() -> bool:
    """True if any process is mid-cycle right now."""
    conn = connect(autocommit=True)
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT count(*) FROM pg_locks WHERE locktype = 'advisory' "
                "  AND classid = %s AND objid = %s AND granted",
                (SYNC_LOCK_KEY >> 32, SYNC_LOCK_KEY & 0xFFFFFFFF),
            )
            return int(cur.fetchone()[0]) > 0
    except Exception:  # noqa: BLE001
        return False
    finally:
        conn.close()


# ---------- Sync watermark ----------
def unsynced_batch(conn, limit: int) -> list[tuple]:
    """Next rows waiting to be sent, in the remote's column order.

    Rows with no id or no model_id are skipped: the remote requires model_id and
    the id is what makes a re-send safe, so those must be backfilled first
    (``python -m app.maintenance prepare-sync``).
    """
    with conn.cursor() as cur:
        cur.execute(
            "SELECT id, image_id, class_name, x_center, y_center, bbox_width, bbox_height, model_id "
            "  FROM product_detections "
            " WHERE synced_at IS NULL AND id IS NOT NULL AND model_id IS NOT NULL "
            " LIMIT %s",
            (limit,),
        )
        return cur.fetchall()


def mark_synced(conn, ids: list[str]) -> int:
    """Stamp synced_at on the rows that made it to the remote."""
    if not ids:
        return 0
    with conn.cursor() as cur:
        cur.execute(
            "UPDATE product_detections SET synced_at = now() WHERE id = ANY(%s)", (ids,)
        )
        updated = cur.rowcount
    if not conn.autocommit:
        conn.commit()
    return updated


def sync_counts() -> dict:
    """Backlog figures for the sync panel.

    ``pending`` deliberately counts only rows that *can* be sent; anything
    missing an id or a model_id is reported separately as blocked.
    """
    conn = connect(autocommit=True)
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT count(*) FILTER (WHERE synced_at IS NULL AND id IS NOT NULL "
                "                        AND model_id IS NOT NULL), "
                "       count(*) FILTER (WHERE synced_at IS NULL AND (id IS NULL "
                "                        OR model_id IS NULL)), "
                "       count(*) FILTER (WHERE synced_at IS NOT NULL) "
                "  FROM product_detections"
            )
            pending, blocked, synced = cur.fetchone()
            return {
                "pending": int(pending),
                "blocked": int(blocked),
                "synced": int(synced),
            }
    finally:
        conn.close()


def recent_activity(limit: int = 50) -> list[dict]:
    """Most recent per-image pipeline events, newest first (Runtime page)."""
    conn = connect(autocommit=True)
    try:
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute(
                "SELECT i.image_id, i.status, i.rows_written, i.reason, i.updated_at, "
                "       i.job_id, j.source_filename "
                "  FROM data_dump_items i JOIN data_dump_jobs j USING (job_id) "
                " WHERE i.status <> 'pending' "
                " ORDER BY i.updated_at DESC LIMIT %s",
                (limit,),
            )
            return [dict(row) for row in cur.fetchall()]
    finally:
        conn.close()


def ledger_stats() -> dict:
    """Size of the dedup ledger, for the Runtime page header."""
    conn = connect(autocommit=True)
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT count(*) FROM image_inference_runs")
            return {"ledger_rows": int(cur.fetchone()[0])}
    finally:
        conn.close()
